name: Update README
on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'  # Path to your scripts/templates
      - 'templates/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate File Table
        run: |
          python .github/workflows/scripts/generate_table.py
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update file table in README" || echo "No changes to commit"
          git push
